MODEL:
  META_ARCHITECTURE: "GeneralizedRCNNSeq"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-101"
  BACKBONE:
    CONV_BODY: 'R-101-C4'
  RPN:
    ANCHOR_SIZES: (64, 128, 256, 512)
    PRE_NMS_TOP_N_TRAIN: 6000
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TRAIN: 600
    POST_NMS_TOP_N_TEST: 600
  ROI_BOX_HEAD:
    NUM_CLASSES: 31
INPUT:
  MIN_SIZE_TRAIN: (540,)
  MAX_SIZE_TRAIN: 960
  MIN_SIZE_TEST: 540
  MAX_SIZE_TEST: 960
DATASETS:
  TRAIN: ('VID_train_seg16',)
  TEST: ('VID_val_seg16',)
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  STEPS: (160000, 240000, 280000)
  MAX_ITER: 320000
  IMS_PER_BATCH: 2
TEST:
  IMS_PER_BATCH: 2
OUTPUT_DIR: "baseline_"
