MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  BACKBONE:
    CONV_BODY: 'R-50-C4'
  RPN:
    ANCHOR_SIZES: (64, 128, 256, 512)
    PRE_NMS_TOP_N_TRAIN: 6000
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TRAIN: 1000
    POST_NMS_TOP_N_TEST: 1000
  ROI_BOX_HEAD:
    NUM_CLASSES: 31
INPUT:
  MIN_SIZE_TRAIN: (600,)
  MAX_SIZE_TRAIN: 1000
  MIN_SIZE_TEST: 600
  MAX_SIZE_TEST: 1000
DATASETS:
  TRAIN: ('VID_train_all',)
  TEST: ('VID_val_all',)
SOLVER:
  MAX_ITER: 640000
  IMS_PER_BATCH: 1
TEST:
  IMS_PER_BATCH: 1
