MODEL:
  META_ARCHITECTURE: "GeneralizedRCNNSeq"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  BACKBONE:
    CONV_BODY: 'R-50-C4'
  RPN:
    ANCHOR_SIZES: (64, 128, 256, 512)
    PRE_NMS_TOP_N_TRAIN: 6000
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TRAIN: 600
    POST_NMS_TOP_N_TEST: 600
    VIDEO_ON: True
  ROI_BOX_HEAD:
    NUM_CLASSES: 31
    VIDEO_ON: True
INPUT:
  MIN_SIZE_TRAIN: (540,)
  MAX_SIZE_TRAIN: 960
  MIN_SIZE_TEST: 540
  MAX_SIZE_TEST: 960
DATASETS:
  TRAIN: ('VID_train_seg16',)
  TEST: ('VID_val_seg16',)
  USE_ANNO_CACHE: True
SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0001
  STEPS: (40000, 80000, 120000)
  MAX_ITER: 160000
  IMS_PER_BATCH: 2
TEST:
  IMS_PER_BATCH: 2
OUTPUT_DIR: "stage3"
